name: Publish

on:
  release:
    types:
      - published

jobs:
  test:
    uses: ./.github/workflows/test.yml

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up python 3.9
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true
          version: 1.2.2

      - name: Install Dependencies
        run: |
          poetry self add "poetry-dynamic-versioning[plugin]"
          poetry install --all-extras

      - name: Build package
        run: |
          poetry build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist

  publish:
    runs-on: ubuntu-latest
    environment: publish
    permissions:
      id-token: write
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
