name: test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python:
          - version: "3.9"
            toxenv: py39
          - version: "3.10"
            toxenv: py310
    env:
      TOXENV: ${{ matrix.python.toxenv }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up python ${{ matrix.python.version }}
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python.version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          installer-parallel: true

      - name: Install tox
        run: |
          pip install tox

      - name: Run tox
        run: |
          tox
